### ISSUE TITLE
Affinity Map

### ISSUE THREAD

**Issue by lauralozanoalvarez** [lpamelalozano/lim-2018-02-ux-marketplace#2]
- Sacar los insights de la entrevista con cliente.
- Sacar los insights de los usuarios,actualizar en base al último avance (cantidad total de entrevistas realizadas 5+) para empezar a sintetizar la información.
- Ver la posibilidad de buscar una herramienta online de Affinity Map para utilizarla en lugar de una foto de los post it en la pizarra.

**Comment by sandramelisa** [comment]
-Ya saque los insigths de la entrevista con cliente dulce creaciòn.
-Ya saque termine de sacar los insights de usuarios.
-Falta buscar la herramienta online de affinity map para plasmarlo.

**Comment by lauralozanoalvarez** [comment]
Encontramos esta web util de affinity map online https://realtimeboard.com/app/dashboard/

**Comment by sandramelisa** [comment]
Termine el affinity map de las entrevistas en herramienta online realtimeboard.
