### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by sandramelisa** [lpamelalozano/lim-2018-02-ux-marketplace#4]
- Redactar el Readme con los últimos avances e ir actualizándolo.

**Comment by lauralozanoalvarez** [comment]
Se añadió objetivos y presupuesto

**Comment by lauralozanoalvarez** [comment]
Readme terminado, queda pendiente subir los archivos a drive (ya están linkeados) y subir la imagen de mapa de sitio

**Comment by lauralozanoalvarez** [comment]
se subió la imagen de mapa de sitio, pendiente verificar links correctos
