### ISSUE TITLE
High fidelity prototype

### ISSUE THREAD

**Issue by sandramelisa** [lpamelalozano/lim-2018-02-ux-marketplace#5]
-Realizar el prototipo de alta fidelidad en Figma.

**Comment by lauralozanoalvarez** [comment]
Se realiza primera pantalla versión desktop / móvil

**Comment by lauralozanoalvarez** [comment]
Se finalizó la versión mobile con interacción en figma, pendiente versión desktop

**Comment by lauralozanoalvarez** [comment]
listo! pendiente subir a drive para documentarlo
